trigger:
  batch: true
  branches:
    include:
      - master

schedules:
- cron: "46 14 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true
  
parameters:
  - name: TestProjects
    type: string
    default: '**/*IntegrationTests.csproj'
    
extends:
  template: devops/base.yml

