trigger:
  batch: true
  branches:
    include:
      - none

schedules:
- cron: "30 6 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true
      
extends:
  template: devops/base.yml

