trigger:
  batch: true
  branches:
    include:
      - master

schedules:
- cron: "54 14 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true
      
extends:
  template: devops/base.yml

